<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Text Compression</title>
</head>
<body>
<h1>Text Compression</h1>

<hr>
<form action="/php/controllers/MainController.php" method="POST">
    <p>Input:<input type=text size=20 name=input></p>
    <input type="submit" value="Run Algorithm" />
</form>

<form action="/php/controllers/MainController.php" method="GET">
    <input type="submit" value="View History" />
</form>
</body>